### ISSUE TITLE
Error load map from server

### ISSUE THREAD

**Issue by vdemidov** [Jezza34000/homeassistant_weback_component#19]
```
2023-05-06 22:24:26.647 INFO (MainThread) [custom_components.weback_vacuum] Creating new Weback Vacuum Robot component
2023-05-06 22:24:26.648 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi __init__
2023-05-06 22:24:26.648 DEBUG (MainThread) [custom_components.weback_vacuum] Weback vacuum robots: login started
2023-05-06 22:24:26.650 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi checking token validity : 2023-05-07 22:18:44.579626
2023-05-06 22:24:26.659 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi token is valid
2023-05-06 22:24:26.659 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi use cached creds.
2023-05-06 22:24:26.659 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi ask : robot list
2023-05-06 22:24:26.660 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] Send HTTP request Url=https://user.grit-cloud.com/prod/api Params={'json': {'opt': 'user_thing_list_get'}, 'headers': {'Token': 'my token', 'Region': 'eu-central-1'}}
2023-05-06 22:24:27.813 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.luci
2023-05-06 22:24:29.038 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi : Send HTTP OK, return=200
2023-05-06 22:24:29.038 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi : HTTP data received = {'msg': 'success', 'code': 1, 'data': {'thing_list': [{'create_timestamp': '1683398261839', 'is_admin': True, 'app_name': 'WeBack', 'sub_type': 'xs-x8', 'tag': 1, 'user_account': 'myemail', 'is_common': True, 'room_id': '7ce975de25604193a1eec1840d131422', 'thing_name': 'xs-x8-1683398249-34-20-03-86-72-ff', 'thing_nickname': 'Arkadiy', 'hardware_version': '0.0', 'batch_num': '0', 'mac': '34-20-03-86-72-ff', 'firmware_version': '1.6.0', 'thing_status': {'Voicebox_Source': 'null', 'battery_level': 58, 'clean_area': 5.0, 'clean_time': 0, 'cliff_detect': 'enable', 'connected': 'true', 'continue_clean': True, 'current_status_percentage': 0, 'error_info': 'NoError', 'extend_function_flag': 7, 'fan_status': 'Normal', 'forbidden_zone_point_num': 4, 'forbidden_zone_x': [23, 23, -19, -19], 'forbidden_zone_y': [-17, -10, -10, -17], 'goto_point': [], 'hismap_id': '3', 'laser_goto_path_point_num': 0, 'laser_goto_path_x': [], 'laser_goto_path_y': [], 'laser_wall_line_point_num': 0, 'laser_wall_line_x': [], 'laser_wall_line_y': [], 'local_ip': '10.1.0.22', 'offset_hours': 0, 'offset_minutes': 0, 'over_ridge': True, 'selected_zone': [], 'undisturb_mode': 'off', 'upgrade_logic': '1.0', 'vendor_firmware_version': '4.00.30', 'vendor_system_version': 'f2e39dec5', 'version_info': '1.2', 'voice_switch': 'on', 'voicepack_id': '003000000000', 'voicepack_version': '3.0.0.0', 'volume': 9, 'water_level': 'None', 'working_status': 'PileCharging', 'ymop_mode': True, 'yugong_software_version': '1.6.0', 'zone_policy_enable': False}, 'brand_icon': 'https://www.grit-cfg.com/device/brand/xs-x8.png'}]}}
2023-05-06 22:24:29.073 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi get robot list OK : [{'create_timestamp': '1683398261839', 'is_admin': True, 'app_name': 'WeBack', 'sub_type': 'xs-x8', 'tag': 1, 'user_account': 'myemail', 'is_common': True, 'room_id': '7ce975de25604193a1eec1840d131422', 'thing_name': 'xs-x8-1683398249-34-20-03-86-72-ff', 'thing_nickname': 'Arkadiy', 'hardware_version': '0.0', 'batch_num': '0', 'mac': '34-20-03-86-72-ff', 'firmware_version': '1.6.0', 'thing_status': {'Voicebox_Source': 'null', 'battery_level': 58, 'clean_area': 5.0, 'clean_time': 0, 'cliff_detect': 'enable', 'connected': 'true', 'continue_clean': True, 'current_status_percentage': 0, 'error_info': 'NoError', 'extend_function_flag': 7, 'fan_status': 'Normal', 'forbidden_zone_point_num': 4, 'forbidden_zone_x': [23, 23, -19, -19], 'forbidden_zone_y': [-17, -10, -10, -17], 'goto_point': [], 'hismap_id': '3', 'laser_goto_path_point_num': 0, 'laser_goto_path_x': [], 'laser_goto_path_y': [], 'laser_wall_line_point_num': 0, 'laser_wall_line_x': [], 'laser_wall_line_y': [], 'local_ip': '10.1.0.22', 'offset_hours': 0, 'offset_minutes': 0, 'over_ridge': True, 'selected_zone': [], 'undisturb_mode': 'off', 'upgrade_logic': '1.0', 'vendor_firmware_version': '4.00.30', 'vendor_system_version': 'f2e39dec5', 'version_info': '1.2', 'voice_switch': 'on', 'voicepack_id': '003000000000', 'voicepack_version': '3.0.0.0', 'volume': 9, 'water_level': 'None', 'working_status': 'PileCharging', 'ymop_mode': True, 'yugong_software_version': '1.6.0', 'zone_policy_enable': False}, 'brand_icon': 'https://www.grit-cfg.com/device/brand/xs-x8.png'}]
2023-05-06 22:24:29.073 DEBUG (MainThread) [custom_components.weback_vacuum] Weback vacuum robots: [{'create_timestamp': '1683398261839', 'is_admin': True, 'app_name': 'WeBack', 'sub_type': 'xs-x8', 'tag': 1, 'user_account': 'myemail', 'is_common': True, 'room_id': '7ce975de25604193a1eec1840d131422', 'thing_name': 'xs-x8-1683398249-34-20-03-86-72-ff', 'thing_nickname': 'Arkadiy', 'hardware_version': '0.0', 'batch_num': '0', 'mac': '34-20-03-86-72-ff', 'firmware_version': '1.6.0', 'thing_status': {'Voicebox_Source': 'null', 'battery_level': 58, 'clean_area': 5.0, 'clean_time': 0, 'cliff_detect': 'enable', 'connected': 'true', 'continue_clean': True, 'current_status_percentage': 0, 'error_info': 'NoError', 'extend_function_flag': 7, 'fan_status': 'Normal', 'forbidden_zone_point_num': 4, 'forbidden_zone_x': [23, 23, -19, -19], 'forbidden_zone_y': [-17, -10, -10, -17], 'goto_point': [], 'hismap_id': '3', 'laser_goto_path_point_num': 0, 'laser_goto_path_x': [], 'laser_goto_path_y': [], 'laser_wall_line_point_num': 0, 'laser_wall_line_x': [], 'laser_wall_line_y': [], 'local_ip': '10.1.0.22', 'offset_hours': 0, 'offset_minutes': 0, 'over_ridge': True, 'selected_zone': [], 'undisturb_mode': 'off', 'upgrade_logic': '1.0', 'vendor_firmware_version': '4.00.30', 'vendor_system_version': 'f2e39dec5', 'version_info': '1.2', 'voice_switch': 'on', 'voicepack_id': '003000000000', 'voicepack_version': '3.0.0.0', 'volume': 9, 'water_level': 'None', 'working_status': 'PileCharging', 'ymop_mode': True, 'yugong_software_version': '1.6.0', 'zone_policy_enable': False}, 'brand_icon': 'https://www.grit-cfg.com/device/brand/xs-x8.png'}]
2023-05-06 22:24:29.074 INFO (MainThread) [custom_components.weback_vacuum] Found robot : xs-x8-1683398249-34-20-03-86-72-ff nickname : Arkadiy
2023-05-06 22:24:29.074 DEBUG (MainThread) [custom_components.weback_vacuum.VacDevice] WebackApi RobotController __init__
2023-05-06 22:24:29.074 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi __init__
2023-05-06 22:24:29.074 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi WSS Control __init__
2023-05-06 22:24:29.079 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi checking token validity : 2023-05-07 22:18:44.579626
2023-05-06 22:24:29.080 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi token is valid
2023-05-06 22:24:29.080 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi use cached creds.
2023-05-06 22:24:29.080 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi ask : get reuse map 3
2023-05-06 22:24:29.080 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] Send HTTP request Url=https://user.grit-cloud.com/prod/api Params={'json': {'opt': 'reuse_map_get', 'map_id': '3', 'sub_type': 'xs-x8', 'thing_name': 'xs-x8-1683398249-34-20-03-86-72-ff'}, 'headers': {'Token': 'mytoken', 'Region': 'eu-central-1'}}
2023-05-06 22:24:29.643 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi : Send HTTP OK, return=200
2023-05-06 22:24:29.643 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi : HTTP data received = {'msg': 'success', 'code': 1, 'data': {'map_data': ''}}
2023-05-06 22:24:29.646 DEBUG (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi get reuse map OK
2023-05-06 22:24:29.647 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback_vacuum
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
result = await task
File "/config/custom_components/weback_vacuum/__init__.py", line 90, in async_setup
await vacuum_device.load_maps()
File "/config/custom_components/weback_vacuum/VacDevice.py", line 45, in load_maps
self.map = VacMap(map_data)
File "/config/custom_components/weback_vacuum/VacMap.py", line 111, in __init__
self.load_data(input)
File "/config/custom_components/weback_vacuum/VacMap.py", line 114, in load_data
self.data = json.loads(zlib.decompress(base64.b64decode(input)))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by vdemidov** [comment]
After full cleaning and saving map in application everything works. But I'm think this is bug.

**Comment by Jezza34000** [comment]
Hi, yes i will fix it in next version :-)
