### ISSUE TITLE
Error during setup of component weback_vacuum

### ISSUE THREAD

**Issue by vdemidov** [Jezza34000/homeassistant_weback_component#22]
Error after update component to version 1.1.3
Log:
```
2023-06-12 13:03:24.407 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback_vacuum
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
result = await task
^^^^^^^^^^
File "/config/custom_components/weback_vacuum/__init__.py", line 62, in async_setup
log_res = await weback_api.login()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/weback_vacuum/webackapi.py", line 87, in login
if self.verify_cached_creds():
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/weback_vacuum/webackapi.py", line 136, in verify_cached_creds
and self.user == creds_data["weback_token"]["user"]
~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'user'
```

**Comment by Jezza34000** [comment]
`rm /root/config/weback_creds`
Reboot HA and it will solve problem

**Comment by Lux315** [comment]
Hey @Jezza34000,

thx for your work.

Ive got the same problem, multiple reboots dont fix it. Worked great before the update.

**Comment by loskutovnick** [comment]
I have another error
`2023-06-13 21:32:31.131 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration weback_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:33:14.335 INFO (MainThread) [custom_components.weback_vacuum] Creating new Weback Vacuum Robot component
2023-06-13 21:33:14.336 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi __init__
2023-06-13 21:33:14.336 DEBUG (MainThread) [custom_components.weback_vacuum] Weback vacuum robots: login started
2023-06-13 21:33:14.340 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi has no or invalid cached creds, renew it...
2023-06-13 21:33:14.341 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] Send HTTP request Url=https://user.grit-cloud.com/prod/oauth Params={'json': {'payload': {'opt': 'login', 'pwd': '87032a88c03d067640e4bbc5ebdfee7f'}, 'header': {'language': 'en', 'app_name': 'WeBack', 'calling_code': '0086', 'api_version': '1.0', 'account': 'l_nick@mail.ru', 'client_id': 'yugong_app'}}}
2023-06-13 21:33:22.262 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi : Send HTTP OK, return=200
2023-06-13 21:33:22.263 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi : HTTP data received = None
2023-06-13 21:33:22.319 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback_vacuum
File "/config/custom_components/weback_vacuum/__init__.py", line 62, in async_setup
File "/config/custom_components/weback_vacuum/webackapi.py", line 92, in login`

**Comment by Jezza34000** [comment]
OK and can you give me lines after ? @loskutovnick

**Comment by loskutovnick** [comment]
log
2023-06-13 21:32:31.114 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:32:31.120 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:32:31.125 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:32:31.131 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration weback_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:32:31.136 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-13 21:33:14.335 INFO (MainThread) [custom_components.weback_vacuum] Creating new Weback Vacuum Robot component
2023-06-13 21:33:14.336 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi __init__
2023-06-13 21:33:14.336 DEBUG (MainThread) [custom_components.weback_vacuum] Weback vacuum robots: login started
2023-06-13 21:33:14.340 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi has no or invalid cached creds, renew it...
2023-06-13 21:33:14.341 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] Send HTTP request Url=https://user.grit-cloud.com/prod/oauth Params={'json': {'payload': {'opt': 'login', 'pwd': '87032a88c03d067640e4bbc5ebdfee7f'}, 'header': {'language': 'en', 'app_name': 'WeBack', 'calling_code': '0086', 'api_version': '1.0', 'account': 'l_nick@mail.ru', 'client_id': 'yugong_app'}}}
2023-06-13 21:33:22.262 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi : Send HTTP OK, return=200
2023-06-13 21:33:22.263 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi : HTTP data received = None
2023-06-13 21:33:22.319 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/weback_vacuum/__init__.py", line 62, in async_setup
    log_res = await weback_api.login()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weback_vacuum/webackapi.py", line 92, in login
    if resp["msg"] == SUCCESS_OK:
       ~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Jezza34000** [comment]
OK, first thing : you have published you password for the entire world. Now change it... 
Second things : You configuration is wrong. You have a mail address in `.ru` and you provide calling_code `0086` which is meaning China ?!
Third thing : I will fix this error, but it will not fix your problem. (WeBack server answer nothing when account and calling code are incoherent.

**Comment by loskutovnick** [comment]
Re-registered to @gmail.com. Region China. The error remains.

**Comment by Jezza34000** [comment]
That not an email problem. You could use any email on any location.
Where are you located ? And when you register which Country/Region are you
providing?


Le mar. 13 juin 2023, 17:56, loskutovnick ***@***.***> a
écrit :

**Comment by Jezza34000** [comment]
Yes i confirm i try it with my WeBack app and it's not working.
It's a WeBack issue. I'm sorry but i can't help you.
If you try to switch your firmware with LibOS i'm interessted in some test to see compatiblity.

**Comment by Jezza34000** [comment]
Looks like your account is now working, but you don't any robot registered ?

Also i fix the issue you got when server answer with "Null", region code "86":
https://github.com/Jezza34000/homeassistant_weback_component/releases/tag/1.1.4

**Comment by loskutovnick** [comment]
The vacuum cleaner is registered only in the China region (86). In other regions registration does not pass. I was left without a vacuum cleaner in the house.
Thank you too!
